<!-- <?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://model" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://model" xmlns:intf="http://model" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
WSDL created by Apache Axis version: 1.4
Built on Apr 22, 2006 (06:55:48 PDT)
 <wsdl:types>
  <schema elementFormDefault="qualified" targetNamespace="http://model" xmlns="http://www.w3.org/2001/XMLSchema">
   <element name="getAllFilms">
    <complexType/>
   </element>
   <element name="getAllFilmsResponse">
    <complexType>
     <sequence>
      <element name="getAllFilmsReturn" type="impl:ArrayOf_xsd_anyType"/>
     </sequence>
    </complexType>
   </element>
   <complexType name="ArrayOf_xsd_anyType">
    <sequence>
     <element maxOccurs="unbounded" minOccurs="0" name="item" type="xsd:anyType"/>
    </sequence>
   </complexType>
   <element name="getFilmByID">
    <complexType>
     <sequence>
      <element name="id" type="xsd:int"/>
     </sequence>
    </complexType>
   </element>
   <element name="getFilmByIDResponse">
    <complexType>
     <sequence>
      <element name="getFilmByIDReturn" type="xsd:anyType"/>
     </sequence>
    </complexType>
   </element>
   <element name="deleteFilmByID">
    <complexType>
     <sequence>
      <element name="id" type="xsd:int"/>
     </sequence>
    </complexType>
   </element>
   <element name="deleteFilmByIDResponse">
    <complexType>
     <sequence>
      <element name="deleteFilmByIDReturn" type="impl:Film"/>
     </sequence>
    </complexType>
   </element>
   <element name="updateFilmToDatabase">
    <complexType>
     <sequence>
      <element name="id" type="xsd:int"/>
      <element name="title" type="xsd:string"/>
      <element name="year" type="xsd:int"/>
      <element name="director" type="xsd:string"/>
      <element name="stars" type="xsd:string"/>
      <element name="review" type="xsd:string"/>
     </sequence>
    </complexType>
   </element>
   <element name="updateFilmToDatabaseResponse">
    <complexType>
     <sequence>
      <element name="updateFilmToDatabaseReturn" type="impl:Film"/>
     </sequence>
    </complexType>
   </element>
   <element name="addFilmToDatabase">
    <complexType>
     <sequence>
      <element name="id" type="xsd:int"/>
      <element name="title" type="xsd:string"/>
      <element name="year" type="xsd:int"/>
      <element name="director" type="xsd:string"/>
      <element name="stars" type="xsd:string"/>
      <element name="review" type="xsd:string"/>
     </sequence>
    </complexType>
   </element>
   <element name="addFilmToDatabaseResponse">
    <complexType>
     <sequence>
      <element name="addFilmToDatabaseReturn" type="impl:Film"/>
     </sequence>
    </complexType>
   </element>
  </schema>
 </wsdl:types>

   <wsdl:message name="updateFilmToDatabaseRequest">

      <wsdl:part element="impl:updateFilmToDatabase" name="parameters">

      </wsdl:part>

   </wsdl:message>

   <wsdl:message name="addFilmToDatabaseResponse">

      <wsdl:part element="impl:addFilmToDatabaseResponse" name="parameters">

      </wsdl:part>

   </wsdl:message>

   <wsdl:message name="getAllFilmsRequest">

      <wsdl:part element="impl:getAllFilms" name="parameters">

      </wsdl:part>

   </wsdl:message>

   <wsdl:message name="deleteFilmByIDResponse">

      <wsdl:part element="impl:deleteFilmByIDResponse" name="parameters">

      </wsdl:part>

   </wsdl:message>

   <wsdl:message name="getFilmByIDRequest">

      <wsdl:part element="impl:getFilmByID" name="parameters">

      </wsdl:part>

   </wsdl:message>

   <wsdl:message name="addFilmToDatabaseRequest">

      <wsdl:part element="impl:addFilmToDatabase" name="parameters">

      </wsdl:part>

   </wsdl:message>

   <wsdl:message name="getAllFilmsResponse">

      <wsdl:part element="impl:getAllFilmsResponse" name="parameters">

      </wsdl:part>

   </wsdl:message>

   <wsdl:message name="getFilmByIDResponse">

      <wsdl:part element="impl:getFilmByIDResponse" name="parameters">

      </wsdl:part>

   </wsdl:message>

   <wsdl:message name="deleteFilmByIDRequest">

      <wsdl:part element="impl:deleteFilmByID" name="parameters">

      </wsdl:part>

   </wsdl:message>

   <wsdl:message name="updateFilmToDatabaseResponse">

      <wsdl:part element="impl:updateFilmToDatabaseResponse" name="parameters">

      </wsdl:part>

   </wsdl:message>

   <wsdl:portType name="FilmDAO">

      <wsdl:operation name="getAllFilms">

         <wsdl:input message="impl:getAllFilmsRequest" name="getAllFilmsRequest">

       </wsdl:input>

         <wsdl:output message="impl:getAllFilmsResponse" name="getAllFilmsResponse">

       </wsdl:output>

      </wsdl:operation>

      <wsdl:operation name="getFilmByID">

         <wsdl:input message="impl:getFilmByIDRequest" name="getFilmByIDRequest">

       </wsdl:input>

         <wsdl:output message="impl:getFilmByIDResponse" name="getFilmByIDResponse">

       </wsdl:output>

      </wsdl:operation>

      <wsdl:operation name="deleteFilmByID">

         <wsdl:input message="impl:deleteFilmByIDRequest" name="deleteFilmByIDRequest">

       </wsdl:input>

         <wsdl:output message="impl:deleteFilmByIDResponse" name="deleteFilmByIDResponse">

       </wsdl:output>

      </wsdl:operation>

      <wsdl:operation name="updateFilmToDatabase">

         <wsdl:input message="impl:updateFilmToDatabaseRequest" name="updateFilmToDatabaseRequest">

       </wsdl:input>

         <wsdl:output message="impl:updateFilmToDatabaseResponse" name="updateFilmToDatabaseResponse">

       </wsdl:output>

      </wsdl:operation>

      <wsdl:operation name="addFilmToDatabase">

         <wsdl:input message="impl:addFilmToDatabaseRequest" name="addFilmToDatabaseRequest">

       </wsdl:input>

         <wsdl:output message="impl:addFilmToDatabaseResponse" name="addFilmToDatabaseResponse">

       </wsdl:output>

      </wsdl:operation>

   </wsdl:portType>

   <wsdl:binding name="FilmDAOSoapBinding" type="impl:FilmDAO">

      <wsdlsoap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

      <wsdl:operation name="getAllFilms">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="getAllFilmsRequest">

            <wsdlsoap:body use="literal"/>

         </wsdl:input>

         <wsdl:output name="getAllFilmsResponse">

            <wsdlsoap:body use="literal"/>

         </wsdl:output>

      </wsdl:operation>

      <wsdl:operation name="getFilmByID">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="getFilmByIDRequest">

            <wsdlsoap:body use="literal"/>

         </wsdl:input>

         <wsdl:output name="getFilmByIDResponse">

            <wsdlsoap:body use="literal"/>

         </wsdl:output>

      </wsdl:operation>

      <wsdl:operation name="deleteFilmByID">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="deleteFilmByIDRequest">

            <wsdlsoap:body use="literal"/>

         </wsdl:input>

         <wsdl:output name="deleteFilmByIDResponse">

            <wsdlsoap:body use="literal"/>

         </wsdl:output>

      </wsdl:operation>

      <wsdl:operation name="updateFilmToDatabase">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="updateFilmToDatabaseRequest">

            <wsdlsoap:body use="literal"/>

         </wsdl:input>

         <wsdl:output name="updateFilmToDatabaseResponse">

            <wsdlsoap:body use="literal"/>

         </wsdl:output>

      </wsdl:operation>

      <wsdl:operation name="addFilmToDatabase">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="addFilmToDatabaseRequest">

            <wsdlsoap:body use="literal"/>

         </wsdl:input>

         <wsdl:output name="addFilmToDatabaseResponse">

            <wsdlsoap:body use="literal"/>

         </wsdl:output>

      </wsdl:operation>

   </wsdl:binding>

   <wsdl:service name="FilmDAOService">

      <wsdl:port binding="impl:FilmDAOSoapBinding" name="FilmDAO">

         <wsdlsoap:address location="http://localhost:8080/DynamicAssignment/services/FilmDAO"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
 -->